import type { Metadata } from "next";
import {  Open_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Customer from "./components/Customer";
import Footer from "./components/Footer";
import localFont from "next/font/local";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const podcast = localFont({
  src: "../public/fonts/Podcast.ttf",
  variable: "--font-podcast",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${openSans.variable} ${podcast.variable} text-gray333 font-sans antialiased`}
      >
        <NavBar/>
        {children}
        <Customer/>
        <Footer/>
      </body>
    </html>
  );
}
